# -*- coding: utf-8 -*-
"""ATT2 das 10 atividades de matrizes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17gnyxYyuLMJZDB9_pkdM9UPRiDDp7h4G
"""

notas = []
for i in range(10):
	linha = [0] * 3
	notas.append(linha)

for i in range(10):
	for j in range(3):
		notas[i][j] = float(input('Digite a nota %d do aluno %d: '% (j+1,i+1)))
q1 = 0
q2 = 0
q3 = 0
for i in range(10):
	menor = notas[i][0]
	menor_p = 0
	for j in range(3):
		if notas[i][j] < menor:
			menor = notas[i][j]
			menor_p = j
	print("Aluno:",i +1, "Prova:",menor_p +1)
	if menor_p == 0:
		q1 += 1
	if menor_p == 1:
		q2 += 1
	if menor_p == 2:
		q3 += 1
print(" Quantidade de menores notas da prova 1:", q1,"\n","Quantidade de menores notas da prova 2:", q2,"\n","Quantidade de menores notas da prova 3:", q3)