# -*- coding: utf-8 -*-
"""custo de carro impostos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W9ek8gPhx5KiEOl2XIh1h_ix7psC2d3o
"""

custo_fabrica = int(input("Insira o valor do custo de fábrica do carro "))
percentagem_dist = 0.28
impostos = 0.45
custo_consumidor = custo_fabrica + (custo_fabrica * percentagem_dist) + (custo_fabrica * impostos)
print(f"O preço para o consumidor sai em: {custo_consumidor} reais.")