# -*- coding: utf-8 -*-
"""Turtle Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iRgzaRzHyxgPegFQ3EyFyCMMetLKO5nV
"""

lista = {
    "1": "Bingus",
    "2": "Floppa",
}



!pip3 install ColabTurtle
from ColabTurtle.Turtle import *



initializeTurtle()

side_length = 20
angle = 360/40

for i in range(10):
  forward(side_length)
  right(angle)

side_length = 20
angle = 360/20

for i in range(20):
  forward(side_length)
  right(angle)